//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniMerit
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RegUser
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please provide Full Name", AllowEmptyStrings =false)]
        public string FullName { get; set; }
        [Required(ErrorMessage = "Please provide Email ID", AllowEmptyStrings =false)]
        [RegularExpression(@"^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", 
            ErrorMessage ="Email ID not valid.")]
        public string EmailID { get; set; }
        [Required(ErrorMessage = "Please provide Password", AllowEmptyStrings =false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage ="Password must be 8 char long.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please confirm Password")]
        [Compare("Password", ErrorMessage ="Confirm Password does not match.")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password )]
        public string confirmPassword { get; set; }
        [Required(ErrorMessage = "Please select Class")]
        public string Class { get; set; }
    }
}
